### ISSUE TITLE
v1 is coming soon...

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#1869]
## 📃 Description

You read that right, FINALLY going to tag `v1.0.0` here soon. This issue is to track all the polishing, chores and final tasks to get to that milestone.

### 🚀 Features

- [x] Implement #1877 

### 🧹 Chores
- [x] Merge #1866 which cleans up InfluxDB integration data types and adds batch writes so you can re-state history.
- [x] Remove "bad data" settings, table and migrations. At this point `v1` will assume you did it, if you haven't now is the time to catch up. #1911 
- [x] Update the repo's documentation. #1914 

### 📖 Documentation
- [x] Merge https://github.com/alexjustesen/speedtest-tracker-docs/pull/48 which updates the install instructions on the docs site.

**Comment by alexjustesen** [comment]
I'm planning on tagging `v1.0.0` on Friday, December 13th provided we don't run into any issues with the blocked servers feature that needs fixing.

Get your testing in asap!
